# Generated by Django 4.0.3 on 2022-05-14 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lancha', '0002_remove_frete_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frete',
            name='data_entrega',
            field=models.DateField(),
        ),
    ]
